const cards = [
    {
        name: "A",
        naipe: "spades",
        value: 1,
        picture: "./images/spadesA.png",
        altText: "ace of spades",
    },
    {
        name: "2",
        naipe: "spades",
        value: 2,
        picture: "./images/spades2.png",
        altText: "two of spades",
    },
    {
        name: "3",
        naipe: "spades",
        value: 3,
        picture: "./images/spades3.png",
        altText: "three of spades",
    },
    {
        name: "4",
        naipe: "spades",
        value: 4,
        picture: "./images/spades4.png",
        altText: "four of spades",
    },
    {
        name: "5",
        naipe: "spades",
        value: 5,
        picture: "./images/spades5.png",
        altText: "five of spades",
    },
    {
        name: "6",
        naipe: "spades",
        value: 6,
        picture: "./images/spades6.png",
        altText: "six of spades",
    },
    {
        name: "7",
        naipe: "spades",
        value: 7,
        picture: "./images/spades7.png",
        altText: "seven of spades",
    },
    {
        name: "8",
        naipe: "spades",
        value: 8,
        picture: "./images/spades8.png",
        altText: "eight of spades",
    },
    {
        name: "9",
        naipe: "spades",
        value: 9,
        picture: "./images/spades9.png",
        altText: "nine of spades",
    },
    {
        name: "10",
        naipe: "spades",
        value: 10,
        picture: "./images/spades10.png",
        altText: "ten of spades",
    },
    {
        name: "Jack",
        naipe: "spades",
        value: 10,
        picture: "./images/spadesJ.png",
        altText: "jack of spades",
    },
    {
        name: "Queen",
        naipe: "spades",
        value: 10,
        picture: "./images/spadesQ.png",
        altText: "queen of spades",
    },
    {
        name: "King",
        naipe: "spades",
        value: 10,
        picture: "./images/spadesK.png",
        altText: "king of spades",
    },
    {
        name: "A",
        naipe: "diamonds",
        value: 1,
        picture: "./images/diamondA.png",
        altText: "ace of diamonds",
    },
    {
        name: "2",
        naipe: "diamonds",
        value: 2,
        picture: "./images/diamond2.png",
        altText: "two of diamonds",
    },
    {
        name: "3",
        naipe: "diamonds",
        value: 3,
        picture: "./images/diamond3.png",
        altText: "three of diamonds",
    },
    {
        name: "4",
        naipe: "diamonds",
        value: 4,
        picture: "./images/diamond4.png",
        altText: "four of diamonds",
    },
    {
        name: "5",
        naipe: "diamonds",
        value: 5,
        picture: "./images/diamond5.png",
        altText: "five of diamonds",
    },
    {
        name: "6",
        naipe: "diamonds",
        value: 6,
        picture: "./images/diamond6.png",
        altText: "six of diamonds",
    },
    {
        name: "7",
        naipe: "diamonds",
        value: 7,
        picture: "./images/diamond7.png",
        altText: "seven of diamonds",
    },
    {
        name: "8",
        naipe: "diamonds",
        value: 8,
        picture: "./images/diamond8.png",
        altText: "eight of diamonds",
    },
    {
        name: "9",
        naipe: "diamonds",
        value: 9,
        picture: "./images/diamond9.png",
        altText: "nine of diamonds",
    },
    {
        name: "10",
        naipe: "diamonds",
        value: 10,
        picture: "./images/diamond10.png",
        altText: "ten of diamonds",
    },
    {
        name: "Jack",
        naipe: "diamonds",
        value: 10,
        picture: "./images/diamondJ.png",
        altText: "jack of diamonds",
    },
    {
        name: "Queen",
        naipe: "diamonds",
        value: 10,
        picture: "./images/diamondQ.png",
        altText: "queen of diamonds",
    },
    {
        name: "King",
        naipe: "diamonds",
        value: 10,
        picture: "./images/diamondK.png",
        altText: "king of diamonds",
    },
    {
        name: "A",
        naipe: "clubs",
        value: 1,
        picture: "./images/clubsA.png",
        altText: "ace of clubs",
    },
    {
        name: "2",
        naipe: "clubs",
        value: 2,
        picture: "./images/clubs2.png",
        altText: "two of clubs",
    },
    {
        name: "3",
        naipe: "clubs",
        value: 3,
        picture: "./images/clubs3.png",
        altText: "three of clubs",
    },
    {
        name: "4",
        naipe: "clubs",
        value: 4,
        picture: "./images/clubs4.png",
        altText: "four of clubs",
    },
    {
        name: "5",
        naipe: "clubs",
        value: 5,
        picture: "./images/clubs5.png",
        altText: "five of clubs",
    },
    {
        name: "6",
        naipe: "clubs",
        value: 6,
        picture: "./images/clubs6.png",
        altText: "six of clubs",
    },
    {
        name: "7",
        naipe: "clubs",
        value: 7,
        picture: "./images/clubs7.png",
        altText: "seven of clubs",
    },
    {
        name: "8",
        naipe: "clubs",
        value: 8,
        picture: "./images/clubs8.png",
        altText: "eight of clubs",
    },
    {
        name: "9",
        naipe: "clubs",
        value: 9,
        picture: "./images/clubs9.png",
        altText: "nine of clubs",
    },
    {
        name: "10",
        naipe: "clubs",
        value: 10,
        picture: "./images/clubs10.png",
        altText: "ten of clubs",
    },
    {
        name: "Jack",
        naipe: "clubs",
        value: 10,
        picture: "./images/clubsJ.png",
        altText: "jack of clubs",
    },
    {
        name: "Queen",
        naipe: "clubs",
        value: 10,
        picture: "./images/clubsQ.png",
        altText: "queen of clubs",
    },
    {
        name: "King",
        naipe: "clubs",
        value: 10,
        picture: "./images/clubsK.png",
        altText: "king of clubs",
    },
    {
        name: "A",
        naipe: "hearts",
        value: 1,
        picture: "./images/heartsA.png",
        altText: "ace of hearts",
    },
    {
        name: "2",
        naipe: "hearts",
        value: 2,
        picture: "./images/hearts2.png",
        altText: "two of hearts",
    },
    {
        name: "3",
        naipe: "hearts",
        value: 3,
        picture: "./images/hearts3.png",
        altText: "three of hearts",
    },
    {
        name: "4",
        naipe: "hearts",
        value: 4,
        picture: "./images/hearts4.png",
        altText: "four of hearts",
    },
    {
        name: "5",
        naipe: "hearts",
        value: 5,
        picture: "./images/hearts5.png",
        altText: "five of hearts",
    },
    {
        name: "6",
        naipe: "hearts",
        value: 6,
        picture: "./images/hearts6.png",
        altText: "six of hearts",
    },
    {
        name: "7",
        naipe: "hearts",
        value: 7,
        picture: "./images/hearts7.png",
        altText: "seven of hearts",
    },
    {
        name: "8",
        naipe: "hearts",
        value: 8,
        picture: "./images/hearts8.png",
        altText: "eight of hearts",
    },
    {
        name: "9",
        naipe: "hearts",
        value: 9,
        picture: "./images/hearts9.png",
        altText: "nine of hearts",
    },
    {
        name: "10",
        naipe: "hearts",
        value: 10,
        picture: "./images/hearts10.png",
        altText: "ten of hearts",
    },
    {
        name: "Jack",
        naipe: "hearts",
        value: 10,
        picture: "./images/heartsJ.png",
        altText: "jack of hearts",
    },
    {
        name: "Queen",
        naipe: "hearts",
        value: 10,
        picture: "./images/heartsQ.png",
        altText: "queen of hearts",
    },
    {
        name: "King",
        naipe: "hearts",
        value: 10,
        picture: "./images/heartsK.png",
        altText: "king of hearts",
    },
];

export { cards };